### ISSUE TITLE
installation with conda

### ISSUE THREAD

**Issue by stephenturner** [dahak-metagenomics/dahak#99]
On https://dahak-metagenomics.github.io/dahak/installing/, might be useful to add installation instructions using conda. Here's an environment i'm building so far (includes some things i need for simulation).

```yaml
name: dahak
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - art
    - nanosim
    - pbsim
    - singularity
    - snakemake
````

```bash
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda

conda env create -f dahak-conda-environment.yml
```
